---

- name: download go-acme/lego
  get_url:
    url: https://github.com/go-acme/lego/releases/download/v{{ lego_version }}/lego_v{{ lego_version }}_linux_386.tar.gz
    dest: /tmp/lego.tar.gz
  when: "'32' in ansible_architecture and 'Linux' == ansible_system"

- name: download go-acme/lego
  get_url:
    url: https://github.com/go-acme/lego/releases/download/v{{ lego_version }}/lego_v{{ lego_version }}_linux_amd64.tar.gz
    dest: /tmp/lego.tar.gz
  when: "'64' in ansible_architecture and 'Linux' == ansible_system"

- name: unzip lego
  unarchive:
    src: /tmp/lego.tar.gz
    dest: /tmp
    remote_src: yes

...
